name: Matrix Workout Data Addon
version: "1.0"
slug: workout_data
description: Exposes workout data via REST API for Home Assistant.
startup: services
boot: auto
ports:
  "5000/tcp": 5000
schema:
  username: str
  password: str
  api_key: str
  debug: bool?
options:
  username: your_username
  password: your_password
  api_key: your_api_key
  debug: false

