name: Matrix Workout Data Addon
version: "2.91"
slug: workout_data
description: Exposes workout data via REST API for Home Assistant.
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "5000/tcp": 5000
schema:
  username: str
  password: str
  api_key: str
  debug: bool?
options:
  username: your_username
  password: your_password
  api_key: your_api_key
  debug: false
